services:
  mariadb:
    image: mariadb:11
    container_name: Maria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daweb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # Aplicaci√≥n Spring Boot
  spring-app:
    build: .
    container_name: ServidorPHP
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/daweb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8085:8080"
    restart: always

volumes:
  mariadb_data:
